[#62] 흡연 구역 조회 API 연결
TeamFogFog/FogFog-iOS pull request #83
Opened 2023-11-21 14:46 UTC by seungchan2

## 🔍 What is this PR?
- 현재 위치 위도 경도에 따라 흡연 구역 조회를 합니다.

## 📝 Changes
- MapService, MapAPI 파일에서 네트워크 코드를 작성했습니다.
- MapViewModel에서는 현재 위치 기반 최초 1회 네트워크 요청하고, 지도가 이동하면 이동한 지도 가운데의 위도 경도를 담아 요청합니다.
- 다음 이슈에서는 줌 비율 계산해서 반영하겠습니당!

## 📸 Screenshot
- 생략

## ☑️ Test Checklist
```swift
Request Message:  Invalid prisma.$queryRaw() invocation:   Raw query failed. Code: 22P03. Message: db error: ERROR: incorrect binary data format in bind parameter 1
Error:
Invalid prisma.$queryRaw() invocation:
Raw query failed. Code: 22P03. Message: db error: ERROR: incorrect binary data format in bind parameter 1
   at RequestHandler.handleRequestError (/var/app/current/node_modules/@prisma/client/runtime/index.js:30873:13)
   at RequestHandler.request (/var/app/current/node_modules/@prisma/client/runtime/index.js:30856:12)
   at Proxy._request (/var/app/current/node_modules/@prisma/client/runtime/index.js:31836:16)
   at MapsService.getMapsByLatAndLong (/var/app/current/src/maps/maps.service.ts:25:43)
   at MapsController.getMapsByLatAndLong (/var/app/current/src/maps/maps.controller.ts:68:7)
``` 
- 다음과 같은 에러가 있었는데,, 흠,, 서버 에러도 아니라고 해서 ,, 오늘 다시 빌드해보니까 되더라구요,,!!!!!!!!

## 📮 관련 이슈

- Resolved: #62

2023-11-24 07:21 UTC, jane1choi requested changes
수고했어!!!!!
리뷰 확인 부탁드립니당 ~

2023-11-24 07:21 UTC, jane1choi commented on FogFog-iOS/FogFog-iOS/Networking/APIs/MapAPI.swift
>      }
p2;
네트워크 요청 헤더 부분 `interceptor`의 `adapt()` 에서 아마 자동으로 들어갈텐데 
`.none` 으로 두고 테스트해 본 다음 문제없으면 지워줘도 될 것 같습니다~!

2023-11-24 07:21 UTC, jane1choi commented on FogFog-iOS/FogFog-iOS/Presentation/Map/MapViewModel.swift
> +    let userNickname = BehaviorSubject<String>(value: UserDefaults.nickname ?? "")
p2;
`UserDefaults` `property wrapper`에 `default`값 설정해두어서 의미없는 값이라면 nil 병합 연산자로 옵셔널 처리 안해줘도 될 것 같습니다!! 옵셔널 처리해준 부분 다 확인하고 삭제해줘도 될 것 같아요~!

2023-11-24 07:21 UTC, jane1choi commented on FogFog-iOS/FogFog-iOS/Presentation/Map/MapViewModel.swift
> +                }
p2;
요기두....  `??` 안써도 될 것 같아요! 확인 부탁쓰 ~

2023-11-24 07:21 UTC, jane1choi commented on FogFog-iOS/FogFog-iOS/Presentation/Map/MapViewModel.swift
> +            .take(1)
`take(1)` 굳...이당..알아갑니다👍🏻

2023-11-24 07:21 UTC, jane1choi commented on FogFog-iOS/FogFog-iOS/Presentation/Map/MapViewModel.swift
> +            .throttle(.seconds(1), scheduler: MainScheduler.instance)
p3;
`skip` operator를 사용하는 이유는 뭔가요??
`throttle`만 사용해주어도 되지 않나 하는 생각이 들어서 질문 남깁니다!

2023-11-24 07:21 UTC, jane1choi commented on FogFog-iOS/FogFog-iOS/Presentation/Map/MapViewModel.swift
> +                print("위경도", roundedLatitude)
p3;
나중에 지도 관련 테스트 완료되면 `print` 문 지워주면 좋을 것 같습니다~

2023-11-24 07:21 UTC, jane1choi commented on FogFog-iOS/FogFog-iOS/Presentation/Map/MapViewModel.swift
> +                owner.userNickname.onNext(UserDefaults.nickname ?? "")
p2;
여기도 확인부탁드립니다!

2023-11-24 08:07 UTC, Taehyeon-Kim requested changes

2023-11-24 08:07 UTC, Taehyeon-Kim commented on FogFog-iOS/FogFog-iOS/Presentation/Map/LocationService.swift
> +    var location: BehaviorRelay<[CLLocation]> { get set }
p2; 선언이 중복된 것 같습니다

2023-11-24 08:07 UTC, Taehyeon-Kim commented on FogFog-iOS/FogFog-iOS/Presentation/Map/MapViewController.swift
> +
p2; 여기도 중복인 것 같습니다

2023-11-24 08:07 UTC, Taehyeon-Kim commented on FogFog-iOS/FogFog-iOS/Presentation/Map/MapViewModel.swift
> +            }
```suggestion
            .flatMap { [weak self] res in
                return self?.networkProvider.fetchPlaceAll(coordinates: CoordinatesRequest(lat: res.first!.coordinate.latitude, long: res.first!.coordinate.longitude))
            }
```
- 약한 참조로 바꿔주세요!

2023-11-24 08:07 UTC, Taehyeon-Kim commented on FogFog-iOS/FogFog-iOS/Presentation/Map/MapViewModel.swift
> +                print("경도", roundedLongitude)
p3; print 지워주세요~

2023-11-24 08:07 UTC, Taehyeon-Kim commented on FogFog-iOS/FogFog-iOS/Presentation/Map/MapViewModel.swift
> +                    dump(res)
p3; 지워주세요!

2023-11-24 08:07 UTC, Taehyeon-Kim commented on FogFog-iOS/FogFog-iOS/Presentation/Map/MapViewModel.swift
> +                if let res {
p3; 위에서 compactMap으로 처리해주면 `if let` 안 쓸 수 있을 것 같습니다.

2023-11-24 08:27 UTC, jane1choi commented on FogFog-iOS/FogFog-iOS/Presentation/Map/MapViewController.swift
> +
헉 예리하다..

2023-11-28 08:55 UTC, seungchan2 commented on FogFog-iOS/FogFog-iOS/Presentation/Map/MapViewModel.swift
> +                }
re:
기존 머지 전에 코드가 살아있어서 Optional 에러가 발생해가꼬 ,, 잠깐 처리해둔건데 반영했습니당

기존 코드가 == nil 처리가 되어있는데 린트 Comparing non-optional value of type 'String' to 'nil' always returns false 에러가 발생하는데 isEmpty로 바꿔놔도 될까용?

2023-11-29 01:23 UTC, jane1choi commented on FogFog-iOS/FogFog-iOS/Presentation/Map/MapViewModel.swift
> +                }
@seungchan2 
굳 당연하쥬

2023-11-30 00:52 UTC, jane1choi approved these changes
확인했습니다!!!! 고생했어~!!!!!!!!!!!

2023-12-16 08:41 UTC, Taehyeon-Kim approved these changes

2023-12-16 08:42 UTC, merged